all:
	python3 fordfulkerson.py ../../tests/testford/flow1.txt ../../tests/testford/outputflow1.txt
	python3 fordfulkerson.py ../../tests/testford/flow2.txt ../../tests/testford/outputflow2.txt
	python3 fordfulkerson.py ../../tests/testford/flow3.txt ../../tests/testford/outputflow3.txt
	python3 fordfulkerson.py ../../tests/testford/flow4.txt ../../tests/testford/outputflow4.txt
	python3 fordfulkerson.py ../../tests/testford/flow5.txt ../../tests/testford/outputflow5.txt
	python3 fordfulkerson.py ../../tests/testford/input.txt ../../tests/testford/output.txt
