all:
	python3 fordfulkerson.py ../../tests/testfordfulkerson/flow1.txt ../../tests/testfordfulkerson/outputflow1.txt
	python3 fordfulkerson.py ../../tests/testfordfulkerson/flow2.txt ../../tests/testfordfulkerson/outputflow2.txt
	python3 fordfulkerson.py ../../tests/testfordfulkerson/flow3.txt ../../tests/testfordfulkerson/outputflow3.txt
	python3 fordfulkerson.py ../../tests/testfordfulkerson/flow4.txt ../../tests/testfordfulkerson/outputflow4.txt
	python3 fordfulkerson.py ../../tests/testfordfulkerson/flow5.txt ../../tests/testfordfulkerson/outputflow5.txt
	python3 fordfulkerson.py ../../tests/testfordfulkerson/input.txt ../../tests/testfordfulkerson/output.txt
